
# Routing for BUS messages
if $msg contains '<undoBUS>' then /var/log/undoLOG/undoBUS.log
& stop

# Routing for base PLC infrastructure
if $msg contains '<undoPLC>' then /var/log/undoLOG/undoPLC.log
& stop

# Routing for user program plc log
if $msg contains '<undoPRG>' then /var/log/undoLOG/undoPRG.log
& stop